<?php

/**
 * BaseBid
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $task_id
 * @property integer $bidder_id
 * @property integer $price
 * @property string $status
 * @property Task $Task
 * @property sfGuardUser $Bidder
 * 
 * @method integer     getTaskId()    Returns the current record's "task_id" value
 * @method integer     getBidderId()  Returns the current record's "bidder_id" value
 * @method integer     getPrice()     Returns the current record's "price" value
 * @method string      getStatus()    Returns the current record's "status" value
 * @method Task        getTask()      Returns the current record's "Task" value
 * @method sfGuardUser getBidder()    Returns the current record's "Bidder" value
 * @method Bid         setTaskId()    Sets the current record's "task_id" value
 * @method Bid         setBidderId()  Sets the current record's "bidder_id" value
 * @method Bid         setPrice()     Sets the current record's "price" value
 * @method Bid         setStatus()    Sets the current record's "status" value
 * @method Bid         setTask()      Sets the current record's "Task" value
 * @method Bid         setBidder()    Sets the current record's "Bidder" value
 * 
 * @package    taskbroker
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBid extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bid');
        $this->hasColumn('task_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('bidder_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('price', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('status', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Task', array(
             'local' => 'task_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as Bidder', array(
             'local' => 'bidder_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}