<?php

/**
 * BaseSuburb
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $postcode
 * @property string $name
 * 
 * @method string getPostcode() Returns the current record's "postcode" value
 * @method string getName()     Returns the current record's "name" value
 * @method Suburb setPostcode() Sets the current record's "postcode" value
 * @method Suburb setName()     Sets the current record's "name" value
 * 
 * @package    taskbroker
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSuburb extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('suburb');
        $this->hasColumn('postcode', 'string', 15, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 15,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}