<?php

/**
 * Bid
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    taskbroker
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Bid extends BaseBid
{
    public function setToAccepted() {
        $this->setStatus(BidTable::$STATUS["accepted"]);
    }
    public function setToRetracted() {
        $this->setStatus(BidTable::$STATUS["retracted"]);
    }
    public function setToRejected() {
        $this->setStatus(BidTable::$STATUS["rejected"]);
    }

    public function getPriceInDollars() { return $this->getPrice() / 100; }

    public function setPriceInDollars($dollars) { $this->setPrice($dollars * 100); }
}
