<?php

/**
 * SuburbTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SuburbTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SuburbTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Suburb');
    }
}