<?php

/**
 * TaskTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TaskTable extends Doctrine_Table
{
    public static $CITY = array(
        "sydney" => "Sydney"
    );
    public static $METHOD = array(
        "cash" => "Cash",
        "direct-deposit" => "Direct Deposit",
        "paypal" => "PayPal"
    );
    public static $PAYMENT = array(
        "upfront" => "Upfront",
        "after-completion" => "After completion"
    );
    
    /**
     * Returns an instance of this class.
     *
     * @return object TaskTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Task');
    }
}