<?php

/**
 * UserProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    taskbroker
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class UserProfile extends BaseUserProfile
{
    public function getStatusName() {
        return ucwords(strtolower(array_search($this->getStatus(),UserProfileTable::$STATUSES)));
        
    }

    public function getTwitterName() {
        if ($this->getTwitter() && $this->getTwitter() != "")
            return "@" . $this->getTwitter();
        return "";
    }

    public function getTwitterURL() {
        if ($this->getTwitter() && $this->getTwitter() != "")
            return "http://www.twitter.com/" . $this->getTwitter ();
        return "";
    }
}
